#!/bin/bash
#Working: bash resolvehosts-json.sh -r domain.com ../chaturbate.com-2018-09-24/chaturbate.com-all-subs-2018-09-24.txt [file path generated by dread]
if [[ $1 == "--resolve" ]] || [[ $1 = "-r" ]]; then
	domain=$2
	file=$3
	mkdir -p Output/$2
	while read domain;
	do
		hoster=$(host $domain | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | awk 'NR==1{print $1; exit}')
		echo "$domain,$hoster" >> Output/$2/hosts.txt
	done < $3
fi
